Tighten lower bound on `base`
Currently this package doesn't work w/ pre-AMP `base` versions:
(while at it, this also sets a more sensible `cabal-version` value and silences the warning about `default-language` missing)

```
Configuring component lib from mnist-idx-0.1.2.7...
Warning: Packages using 'cabal-version: >= 1.10' must specify the 'default-language' field for each component (e.g. Haskell98 or Haskell2010). If a component uses different languages in different modules then list the other ones in the 'other-languages' field.
Preprocessing library mnist-idx-0.1.2.7...
[1 of 2] Compiling Data.IDX.Internal ( src/Data/IDX/Internal.hs, /tmp/matrix-worker/1490622584/dist-newstyle/build/x86_64-linux/ghc-7.8.4/mnist-idx-0.1.2.7/build/Data/IDX/Internal.o )

src/Data/IDX/Internal.hs:70:35: Not in scope: ‘<$>’

src/Data/IDX/Internal.hs:73:62: Not in scope: ‘<$>’

src/Data/IDX/Internal.hs:113:28: Not in scope: ‘<$>’

src/Data/IDX/Internal.hs:114:55: Not in scope: ‘<$>’

src/Data/IDX/Internal.hs:210:51: Not in scope: ‘<$>’

src/Data/IDX/Internal.hs:224:49: Not in scope: ‘<$>’

```